packages:
  ${project.groupId}.domain.issue:
    - issue
    - issue_status
  ${project.groupId}.domain.hello:
    - hello
  ${project.groupId}.domain.tracker:
    - tracker
    - tracker_issue_status
baseClassDefs:
  - tables:
      - "issue"
      - "issue_status"
      - "tracker"
      - "tracker_issue_status"
    baseClass: ${project.groupId}.arch.jpa.BaseEntity
annotationDefs:
  GenerationType.IDENTITY:
    type: jakarta.persistence.GeneratedValue
    attributes:
      strategy: jakarta.persistence.GenerationType.IDENTITY
annotatedCols:
  issue.id:
    - GenerationType.IDENTITY
excludedColmuns:
  - version
  - created_by
  - created_at
  - updated_by
  - updated_at
excludedTables:
  - flyway_schema_history
formatter: google
