@startuml application-structure

skinparam rectangle {
  backgroundColor white
}

actor User

component Svelte <<Frontend>>
component Quarkus <<Backend>>
database PostgreSQL <<DB>>

User -> Svelte: HTTP \n(with Browser)
Svelte -> Quarkus: HTTP
Quarkus -> PostgreSQL: JDBC

rectangle "* User Interface\n* Validatioin\n* Web API Call" as fnote {
}
Svelte .. fnote

rectangle "* Web API\n* Validation\n* Transaction\n* Business Logic\n* DB Access" as bnote {
}
Quarkus .. bnote