@startuml search-page-init

hide footbox
autonumber

actor User

box "Frontend" #ffffff
  participant Page
  participant PageLoader
end box

box "Backend" #ffffff
  participant Controller
  participant Factory
  participant Service
  participant Search
end box

database DB

User -> Page: navigate
Page -> PageLoader: load
PageLoader -> Controller: POST condidion \l model -> dto

Controller -> Factory: build(condition) \n dto -> vo
autonumber stop
Controller <-- Factory
autonumber resume
Controller -> Service: search(condition)
Service -> SearchExecutor: search(condition)
SearchExecutor -> DB: SELECT COUNT
autonumber stop
SearchExecutor <-- DB: count
alt count > 0
  autonumber resume
  SearchExecutor -> DB: SELECT
  autonumber stop
  SearchExecutor <-- DB
end alt
Service <-- SearchExecutor: result
Controller <-- Service: result
autonumber resume
Controller -> Factory: build(result) \l vo -> dto
autonumber stop
Controller <-- Factory

PageLoader <-- Controller: result \l model <- dto 
Page <-- PageLoader: result
