@startuml search-page-init

hide footbox
autonumber

actor User

box "Frontend" #ffffff
  participant Page
  participant PageLoader
end box


User -> Page: action
Page -> Page: navigate\nwith criteria
group Initialization process
  Page -> PageLoader: load
end