@startuml search-page-init

hide footbox
autonumber

actor User

box "Frontend" #ffffff
  participant Page
end box

box "Backend" #ffffff
  participant Controller
end box

User -> Page: action
Page -> Controller: POST condidion \l model -> dto
autonumber stop
Controller -> : 
Page <-- Controller: result \l model <- dto
autonumber resume
Page -> Page: render
